### ISSUE TITLE
Funcionalidad pendiente: Cambiar estado de una tarea

### ISSUE THREAD

**Issue by saulrodtorres** [saulrodtorres/listas.srttorres.es#1]
Actualmente no es posible cambiar el estado de una tarea.
Los estados deberían ser:
Pendiente
Terminada/Completada/Finalizada
Iniciada

**Comment by srttorres** [comment]
Done:
With Django Templates. The code is Horrendus and It's not even a nice design but it works hahaha

**Comment by srttorres** [comment]
I'm going a add another issue to to the same with js and the DOM, using getElementById() function
